steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:latest'
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-commit'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
    waitFor: ['build']

  # Step 3: Update container on Compute Engine instance
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'update-container'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh flask-backend-instance \
          --zone=us-central1-a \
          --command="bash -c 'gcloud auth configure-docker ${_REGION}-docker.pkg.dev && docker pull ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:latest && docker stop flask-backend || true && docker rm flask-backend || true && docker run -d -p 5000:5000 --name flask-backend --restart=always ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:latest && docker ps'"
    waitFor: ['push']

# Images to be pushed to the registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'

# Substitution variables (customize these)
substitutions:
  _REGION: 'us'
  _REGISTRY_NAME: 'docker-repo'
  _IMAGE_NAME: 'fadil-backend'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

timeout: '1800s'
